version: '3.7'

services:
  api:
    container_name: gost_requests

    build: .
    restart: always
    ports:
      - 8000:8000
    expose:
      - 8000

  nginx:
    image: erangaeb/senznginx:0.4
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    links:
      - api